compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

# Uncomment this when working without the Nexus server running.
# npmAlwaysAuth: false
# npmRegistryServer: "https://registry.yarnpkg.com/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
