enableTelemetry: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAlwaysAuth: true
npmRegistryServer: http://localhost:8081/repository/npm-all/

yarnPath: .yarn/releases/yarn-remote.cjs
