# Support "http" for Local Nexus Repository Manager dependency cache.
enableStrictSsl: false

# Do not track by default.
enableTelemetry: false

# Only hoist dependencies at the workspace level.
nmHoistingLimits: workspaces

# Use classic npm link behavior.
nodeLinker: node-modules

# Nexus Repository Manager dependency cache.
npmAlwaysAuth: true
npmRegistryServer: http://localhost:8081/repository/npm-all/

# Allow "http" from "localhost".
unsafeHttpWhitelist:
    - localhost

# Path to the pinned version of yarn.
yarnPath: .yarn/releases/yarn-remote.cjs
