compressionLevel: mixed

enableGlobalCache: true

# Do not track.
enableTelemetry: false

# Only hoist dependencies at the workspace level.
nmHoistingLimits: workspaces

# Use classic npm link behavior.
nodeLinker: node-modules

# Path to the pinned version of yarn.
yarnPath: .yarn/releases/yarn-4.1.1.cjs
