enableStrictSsl: false
enableTelemetry: false

logFilters:
  # Backstage intentionally supports multiple versions of Material UI on
  # React. The following log filter is to suppress the warning message.
  - pattern: '*react* is listed by your project with version*'
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAlwaysAuth: true
npmRegistryServer: http://localhost:8081/repository/npm-all/

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.1.1.cjs
