# Support "http" for Local Nexus Repository Manager dependency cache.
enableStrictSsl: false

# Do not track by default.
enableTelemetry: false

logFilters:
  # Backstage intentionally supports multiple versions of Material UI on
  # React. The following log filter is to suppress the warning message.
  - pattern: '*react* is listed by your project with version*'
    level: discard

# Backstage only works with the "none" setting.
nmHoistingLimits: none

# Use classic npm link behavior.
nodeLinker: node-modules

# Nexus Repository Manager dependency cache.
npmAlwaysAuth: true
npmRegistryServer: http://localhost:8081/repository/npm-all/

# Allow "http" from "localhost".
unsafeHttpWhitelist:
    - localhost

# Path to the pinned version of yarn.
yarnPath: .yarn/releases/yarn-remote.cjs
