enableTelemetry: false

logFilters:
  # Backstage uses both Material UI v4 and v5 with internal dependencies on
  # different versions of react. This is a known issue and can be safely
  # ignored.
  - level: discard
    pattern: "*react* is listed by your project with version 18.*, which doesn't satisfy what @backstage/core-components"

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  # Backstage uses both Material UI v4 and v5. This is a known issue and can
  # be safely ignored.
  - '@material-ui/core (deprecation)'

yarnPath: .yarn/releases/yarn-remote.cjs
