enableGlobalCache: true

# Do not track.
enableTelemetry: false

logFilters:
  - level: discard
    pattern: '*react* is listed by your project with version*'

nmHoistingLimits: none

nodeLinker: node-modules

# Path to the pinned version of yarn.
yarnPath: .yarn/releases/yarn-4.1.1.cjs
