# Continuous integration (CI) for the main repository.
name: repository_ci

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed

env:
    CI: true

defaults:
    run:
        shell: bash

jobs:
    build:
        name: 'repository_ci'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

            - id: upgrade-yarn
              name: Upgrade yarn
              run: |
                  yarn set version $(find ./.yarn/releases/*.cjs -type f)

            - id: install-node
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
              with:
                  node-version-file: './.node-version'
                  cache: 'yarn'
                  cache-dependency-path: '**/yarn.lock'

            - id: cache-wireit
              name: Setup Wireit cache
              uses: google/wireit@setup-github-actions-caching/v1

            - id: make
              name: make
              run: make
